spring:
  application:
    name: dasibom

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:dasibom}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update           
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: Asia/Seoul
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      # password: ${REDIS_PASSWORD:}  # 비밀번호 쓰면 주석 해제

server:
  port: ${APP_PORT:8080}

ml:
  base-url: ${ML_BASE_URL:http://localhost:8000}

logging:
  level:
    org.hibernate.SQL: info
    org.springframework: info
